In [ ]:
!pip install basedosdados==1.6.5

In [ ]:
!pip install pandas

In [2]:
import pandas as pd
import numpy as np
#import basedosdados as bd

## 2022

In [142]:
import pandas as pd
import numpy as np
#coleta dados de 2022
#primeira tabela:T27
path = 'input/anuario-2023.xlsx'
df113 = pd.read_excel(path, sheet_name='T27', skiprows=4, skipfooter=7, dtype=str)
df113.drop(index = [3,5], inplace = True)
df113.drop(columns = ['Unnamed: 5','Unnamed: 10'], inplace = True)

df113.columns = np.hstack([np.array(['sigla_uf'],dtype=str),
                    np.array(['homicidio_mulheres']*4,dtype=str),
                    np.array(['feminicidio']*4,dtype=str),
                    np.array(['proporcao_feminicidio_homicidio_mulheres']*2)],dtype=str)
mapping = {'Brasil':'BR',
          'Acre': 'AC',
          'Alagoas':'AL',
          'Amapá': 'AP',
          'Amazonas':'AM',
          'Bahia':'BA',
          'Ceará':'CE',
          'Distrito Federal':'DF',
          'Espírito Santo':'ES',
          'Goiás':'GO',
          'Maranhão':'MA',
          'Mato Grosso': 'MT',
          'Mato Grosso do Sul': 'MS',
          'Minas Gerais':'MG',
          'Pará': 'PA',
          'Paraíba':'PB',
          'Paraná': 'PR',
          'Pernambuco': 'PE',
          'Piauí':'PI',
          'Rio de Janeiro':'RJ',
          'Rio Grande do Norte':'RN',
          'Rio Grande do Sul':'RS',
          'Rondônia':'RO',
          'Roraima':'RR',
          'Santa Catarina':'SC',
          'São Paulo':'SP',
          'Sergipe':'SE',
          'Tocantins':'TO'}

df113.iloc[2,1:] = np.array(['2021','2022']*5)
df113.iloc[1,1:] = np.hstack([np.array(['n_absolutos','n_absolutos','taxa','taxa']*2),
                             np.array(['taxa','taxa'])])

array1 = df113.columns.values[1:]
array2 = df113.iloc[1,1:]
array3 = df113.iloc[2,1:]

df113.drop(index = [0,1,2], inplace = True)
df113.set_index('sigla_uf', inplace = True)
df113.rename(index = mapping, inplace=True)


arrays = [array1,
         array2,
         array3]


df113.columns = pd.MultiIndex.from_arrays(arrays, names=('tipo', 'medida', 'ano'))
df113 = df113.stack().stack().reset_index()

In [143]:
df113

tipo,sigla_uf,ano,medida,feminicidio,homicidio_mulheres,proporcao_feminicidio_homicidio_mulheres
0,BR,2021,n_absolutos,1347,3965,NaN
1,BR,2021,taxa,1.3042849938230765,3.839265033785077,33.97225725094577
2,BR,2022,n_absolutos,1437,4034,NaN
3,BR,2022,taxa,1.3842101390811934,3.8858063333705872,35.622211204759545
4,AC,2021,n_absolutos,12,29,NaN
...,...,...,...,...,...,...
107,SE,2022,taxa,1.6600070935832993,3.2326453927674783,51.35135135135135
108,TO,2021,n_absolutos,22,39,NaN
109,TO,2021,taxa,2.9490654218288537,5.227888702332968,56.41025641025641
110,TO,2022,n_absolutos,14,36,NaN
111,TO,2022,taxa,1.8619345121453403,4.787831602659447,38.88888888888889